/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: agustin.trezza (https://sketchfab.com/agustin.trezza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-1-e6a5af39d2b3495fb4fb1f8f94d3efda
Title: Javascript (1)
*/
import {useRef} from "react"
import {useGLTF} from '@react-three/drei'
import {JSLogoGLTF, JSLogoProps} from "../types.ts"
import * as THREE from "three"
import {useGSAP} from "@gsap/react"
import gsap from "gsap"

export default function JavascriptLogo(props: JSLogoProps) {

  const JSLogoRef = useRef<THREE.Mesh | null>(null)
  const { nodes, materials } = useGLTF('/models/javascript_1.glb') as unknown as JSLogoGLTF

  useGSAP(() => {
    // @ts-expect-error/ possible nulls can not be addressed, but we know it is not null
    gsap.to(JSLogoRef.current?.position, {
      // @ts-expect-error/ possible nulls can not be addressed, but we know it is not null
      y: JSLogoRef.current?.position?.y + 0.5,
      duration: 1.5,
      yoyo: true,
      repeat: -1,
    })
  })

  return (
      <mesh
        {...props}
        ref={JSLogoRef}
        scale={0.13}
        geometry={nodes.Object_2.geometry}
        material={materials.mat_3220964}
        rotation={[0, 0, 1.8]}
      />
  )
}

useGLTF.preload('/models/javascript_1.glb')