/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/
import { useGLTF, Float } from '@react-three/drei'
import { ReactLogoProps, ReactLogoGLTF } from "../types.ts"
import {useMediaQuery} from "react-responsive";

export default function ReactLogo (props: ReactLogoProps) {

  const { nodes, materials } = useGLTF('/models/react.glb') as unknown as ReactLogoGLTF

  const isSmall = useMediaQuery({ maxWidth: 440 })
  const isMobile = useMediaQuery({ maxWidth: 768 })
  const isTablet = useMediaQuery({ maxWidth: 1024, minWidth: 768 })

  return (
    <Float floatIntensity={1}>
      <group scale={0.5} dispose={null} {...props}>
        <mesh
          geometry={nodes['React-Logo_Material002_0'].geometry}
          material={materials['Material.002']}
          position={[0, 0.079, 0.181]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={isSmall ? [0.30, 0.30, 0.5] : isMobile ? [0.30, 0.30, 0.5] : isTablet ? [0.39, 0.39, 0.5] : [0.39, 0.39, 0.5]}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/react.glb')